MKSHELL=/bin/bash
#Definir MKSHELL ahora debe ir siempre arriba con /bin/bash. "Todo lo que viene a continuación interprétalo con bash"

#Este bloque simplifica el vcf con bcftools para hacerlo más fácilmente manipulable
%.tagged.bed:Q: %.bed
	echo "Adding file name as las column for $prereq"
	awk '
	function basename(file, a, n) {
    n = split(file, a, "/")
    return a[n]
  	}
  	{print $0, basename(FILENAME)}
		' $prereq > $target.build \
		&& mv $target.build $target
